################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../sofa/a2af.c \
../sofa/a2tf.c \
../sofa/ab.c \
../sofa/af2a.c \
../sofa/anp.c \
../sofa/anpm.c \
../sofa/apcg.c \
../sofa/apcg13.c \
../sofa/apci.c \
../sofa/apci13.c \
../sofa/apco.c \
../sofa/apco13.c \
../sofa/apcs.c \
../sofa/apcs13.c \
../sofa/aper.c \
../sofa/aper13.c \
../sofa/apio.c \
../sofa/apio13.c \
../sofa/atci13.c \
../sofa/atciq.c \
../sofa/atciqn.c \
../sofa/atciqz.c \
../sofa/atco13.c \
../sofa/atic13.c \
../sofa/aticq.c \
../sofa/aticqn.c \
../sofa/atio13.c \
../sofa/atioq.c \
../sofa/atoc13.c \
../sofa/atoi13.c \
../sofa/atoiq.c \
../sofa/bi00.c \
../sofa/bp00.c \
../sofa/bp06.c \
../sofa/bpn2xy.c \
../sofa/c2i00a.c \
../sofa/c2i00b.c \
../sofa/c2i06a.c \
../sofa/c2ibpn.c \
../sofa/c2ixy.c \
../sofa/c2ixys.c \
../sofa/c2s.c \
../sofa/c2t00a.c \
../sofa/c2t00b.c \
../sofa/c2t06a.c \
../sofa/c2tcio.c \
../sofa/c2teqx.c \
../sofa/c2tpe.c \
../sofa/c2txy.c \
../sofa/cal2jd.c \
../sofa/cp.c \
../sofa/cpv.c \
../sofa/cr.c \
../sofa/d2dtf.c \
../sofa/d2tf.c \
../sofa/dat.c \
../sofa/dtdb.c \
../sofa/dtf2d.c \
../sofa/eceq06.c \
../sofa/ecm06.c \
../sofa/ee00.c \
../sofa/ee00a.c \
../sofa/ee00b.c \
../sofa/ee06a.c \
../sofa/eect00.c \
../sofa/eform.c \
../sofa/eo06a.c \
../sofa/eors.c \
../sofa/epb.c \
../sofa/epb2jd.c \
../sofa/epj.c \
../sofa/epj2jd.c \
../sofa/epv00.c \
../sofa/eqec06.c \
../sofa/eqeq94.c \
../sofa/era00.c \
../sofa/fad03.c \
../sofa/fae03.c \
../sofa/faf03.c \
../sofa/faju03.c \
../sofa/fal03.c \
../sofa/falp03.c \
../sofa/fama03.c \
../sofa/fame03.c \
../sofa/fane03.c \
../sofa/faom03.c \
../sofa/fapa03.c \
../sofa/fasa03.c \
../sofa/faur03.c \
../sofa/fave03.c \
../sofa/fk52h.c \
../sofa/fk5hip.c \
../sofa/fk5hz.c \
../sofa/fw2m.c \
../sofa/fw2xy.c \
../sofa/g2icrs.c \
../sofa/gc2gd.c \
../sofa/gc2gde.c \
../sofa/gd2gc.c \
../sofa/gd2gce.c \
../sofa/gmst00.c \
../sofa/gmst06.c \
../sofa/gmst82.c \
../sofa/gst00a.c \
../sofa/gst00b.c \
../sofa/gst06.c \
../sofa/gst06a.c \
../sofa/gst94.c \
../sofa/h2fk5.c \
../sofa/hfk5z.c \
../sofa/icrs2g.c \
../sofa/ir.c \
../sofa/jd2cal.c \
../sofa/jdcalf.c \
../sofa/ld.c \
../sofa/ldn.c \
../sofa/ldsun.c \
../sofa/lteceq.c \
../sofa/ltecm.c \
../sofa/lteqec.c \
../sofa/ltp.c \
../sofa/ltpb.c \
../sofa/ltpecl.c \
../sofa/ltpequ.c \
../sofa/num00a.c \
../sofa/num00b.c \
../sofa/num06a.c \
../sofa/numat.c \
../sofa/nut00a.c \
../sofa/nut00b.c \
../sofa/nut06a.c \
../sofa/nut80.c \
../sofa/nutm80.c \
../sofa/obl06.c \
../sofa/obl80.c \
../sofa/p06e.c \
../sofa/p2pv.c \
../sofa/p2s.c \
../sofa/pap.c \
../sofa/pas.c \
../sofa/pb06.c \
../sofa/pdp.c \
../sofa/pfw06.c \
../sofa/plan94.c \
../sofa/pm.c \
../sofa/pmat00.c \
../sofa/pmat06.c \
../sofa/pmat76.c \
../sofa/pmp.c \
../sofa/pmpx.c \
../sofa/pmsafe.c \
../sofa/pn.c \
../sofa/pn00.c \
../sofa/pn00a.c \
../sofa/pn00b.c \
../sofa/pn06.c \
../sofa/pn06a.c \
../sofa/pnm00a.c \
../sofa/pnm00b.c \
../sofa/pnm06a.c \
../sofa/pnm80.c \
../sofa/pom00.c \
../sofa/ppp.c \
../sofa/ppsp.c \
../sofa/pr00.c \
../sofa/prec76.c \
../sofa/pv2p.c \
../sofa/pv2s.c \
../sofa/pvdpv.c \
../sofa/pvm.c \
../sofa/pvmpv.c \
../sofa/pvppv.c \
../sofa/pvstar.c \
../sofa/pvtob.c \
../sofa/pvu.c \
../sofa/pvup.c \
../sofa/pvxpv.c \
../sofa/pxp.c \
../sofa/refco.c \
../sofa/rm2v.c \
../sofa/rv2m.c \
../sofa/rx.c \
../sofa/rxp.c \
../sofa/rxpv.c \
../sofa/rxr.c \
../sofa/ry.c \
../sofa/rz.c \
../sofa/s00.c \
../sofa/s00a.c \
../sofa/s00b.c \
../sofa/s06.c \
../sofa/s06a.c \
../sofa/s2c.c \
../sofa/s2p.c \
../sofa/s2pv.c \
../sofa/s2xpv.c \
../sofa/sepp.c \
../sofa/seps.c \
../sofa/sp00.c \
../sofa/starpm.c \
../sofa/starpv.c \
../sofa/sxp.c \
../sofa/sxpv.c \
../sofa/taitt.c \
../sofa/taiut1.c \
../sofa/taiutc.c \
../sofa/tcbtdb.c \
../sofa/tcgtt.c \
../sofa/tdbtcb.c \
../sofa/tdbtt.c \
../sofa/tf2a.c \
../sofa/tf2d.c \
../sofa/tr.c \
../sofa/trxp.c \
../sofa/trxpv.c \
../sofa/tttai.c \
../sofa/tttcg.c \
../sofa/tttdb.c \
../sofa/ttut1.c \
../sofa/ut1tai.c \
../sofa/ut1tt.c \
../sofa/ut1utc.c \
../sofa/utctai.c \
../sofa/utcut1.c \
../sofa/xy06.c \
../sofa/xys00a.c \
../sofa/xys00b.c \
../sofa/xys06a.c \
../sofa/zp.c \
../sofa/zpv.c \
../sofa/zr.c 

OBJS += \
./sofa/a2af.o \
./sofa/a2tf.o \
./sofa/ab.o \
./sofa/af2a.o \
./sofa/anp.o \
./sofa/anpm.o \
./sofa/apcg.o \
./sofa/apcg13.o \
./sofa/apci.o \
./sofa/apci13.o \
./sofa/apco.o \
./sofa/apco13.o \
./sofa/apcs.o \
./sofa/apcs13.o \
./sofa/aper.o \
./sofa/aper13.o \
./sofa/apio.o \
./sofa/apio13.o \
./sofa/atci13.o \
./sofa/atciq.o \
./sofa/atciqn.o \
./sofa/atciqz.o \
./sofa/atco13.o \
./sofa/atic13.o \
./sofa/aticq.o \
./sofa/aticqn.o \
./sofa/atio13.o \
./sofa/atioq.o \
./sofa/atoc13.o \
./sofa/atoi13.o \
./sofa/atoiq.o \
./sofa/bi00.o \
./sofa/bp00.o \
./sofa/bp06.o \
./sofa/bpn2xy.o \
./sofa/c2i00a.o \
./sofa/c2i00b.o \
./sofa/c2i06a.o \
./sofa/c2ibpn.o \
./sofa/c2ixy.o \
./sofa/c2ixys.o \
./sofa/c2s.o \
./sofa/c2t00a.o \
./sofa/c2t00b.o \
./sofa/c2t06a.o \
./sofa/c2tcio.o \
./sofa/c2teqx.o \
./sofa/c2tpe.o \
./sofa/c2txy.o \
./sofa/cal2jd.o \
./sofa/cp.o \
./sofa/cpv.o \
./sofa/cr.o \
./sofa/d2dtf.o \
./sofa/d2tf.o \
./sofa/dat.o \
./sofa/dtdb.o \
./sofa/dtf2d.o \
./sofa/eceq06.o \
./sofa/ecm06.o \
./sofa/ee00.o \
./sofa/ee00a.o \
./sofa/ee00b.o \
./sofa/ee06a.o \
./sofa/eect00.o \
./sofa/eform.o \
./sofa/eo06a.o \
./sofa/eors.o \
./sofa/epb.o \
./sofa/epb2jd.o \
./sofa/epj.o \
./sofa/epj2jd.o \
./sofa/epv00.o \
./sofa/eqec06.o \
./sofa/eqeq94.o \
./sofa/era00.o \
./sofa/fad03.o \
./sofa/fae03.o \
./sofa/faf03.o \
./sofa/faju03.o \
./sofa/fal03.o \
./sofa/falp03.o \
./sofa/fama03.o \
./sofa/fame03.o \
./sofa/fane03.o \
./sofa/faom03.o \
./sofa/fapa03.o \
./sofa/fasa03.o \
./sofa/faur03.o \
./sofa/fave03.o \
./sofa/fk52h.o \
./sofa/fk5hip.o \
./sofa/fk5hz.o \
./sofa/fw2m.o \
./sofa/fw2xy.o \
./sofa/g2icrs.o \
./sofa/gc2gd.o \
./sofa/gc2gde.o \
./sofa/gd2gc.o \
./sofa/gd2gce.o \
./sofa/gmst00.o \
./sofa/gmst06.o \
./sofa/gmst82.o \
./sofa/gst00a.o \
./sofa/gst00b.o \
./sofa/gst06.o \
./sofa/gst06a.o \
./sofa/gst94.o \
./sofa/h2fk5.o \
./sofa/hfk5z.o \
./sofa/icrs2g.o \
./sofa/ir.o \
./sofa/jd2cal.o \
./sofa/jdcalf.o \
./sofa/ld.o \
./sofa/ldn.o \
./sofa/ldsun.o \
./sofa/lteceq.o \
./sofa/ltecm.o \
./sofa/lteqec.o \
./sofa/ltp.o \
./sofa/ltpb.o \
./sofa/ltpecl.o \
./sofa/ltpequ.o \
./sofa/num00a.o \
./sofa/num00b.o \
./sofa/num06a.o \
./sofa/numat.o \
./sofa/nut00a.o \
./sofa/nut00b.o \
./sofa/nut06a.o \
./sofa/nut80.o \
./sofa/nutm80.o \
./sofa/obl06.o \
./sofa/obl80.o \
./sofa/p06e.o \
./sofa/p2pv.o \
./sofa/p2s.o \
./sofa/pap.o \
./sofa/pas.o \
./sofa/pb06.o \
./sofa/pdp.o \
./sofa/pfw06.o \
./sofa/plan94.o \
./sofa/pm.o \
./sofa/pmat00.o \
./sofa/pmat06.o \
./sofa/pmat76.o \
./sofa/pmp.o \
./sofa/pmpx.o \
./sofa/pmsafe.o \
./sofa/pn.o \
./sofa/pn00.o \
./sofa/pn00a.o \
./sofa/pn00b.o \
./sofa/pn06.o \
./sofa/pn06a.o \
./sofa/pnm00a.o \
./sofa/pnm00b.o \
./sofa/pnm06a.o \
./sofa/pnm80.o \
./sofa/pom00.o \
./sofa/ppp.o \
./sofa/ppsp.o \
./sofa/pr00.o \
./sofa/prec76.o \
./sofa/pv2p.o \
./sofa/pv2s.o \
./sofa/pvdpv.o \
./sofa/pvm.o \
./sofa/pvmpv.o \
./sofa/pvppv.o \
./sofa/pvstar.o \
./sofa/pvtob.o \
./sofa/pvu.o \
./sofa/pvup.o \
./sofa/pvxpv.o \
./sofa/pxp.o \
./sofa/refco.o \
./sofa/rm2v.o \
./sofa/rv2m.o \
./sofa/rx.o \
./sofa/rxp.o \
./sofa/rxpv.o \
./sofa/rxr.o \
./sofa/ry.o \
./sofa/rz.o \
./sofa/s00.o \
./sofa/s00a.o \
./sofa/s00b.o \
./sofa/s06.o \
./sofa/s06a.o \
./sofa/s2c.o \
./sofa/s2p.o \
./sofa/s2pv.o \
./sofa/s2xpv.o \
./sofa/sepp.o \
./sofa/seps.o \
./sofa/sp00.o \
./sofa/starpm.o \
./sofa/starpv.o \
./sofa/sxp.o \
./sofa/sxpv.o \
./sofa/taitt.o \
./sofa/taiut1.o \
./sofa/taiutc.o \
./sofa/tcbtdb.o \
./sofa/tcgtt.o \
./sofa/tdbtcb.o \
./sofa/tdbtt.o \
./sofa/tf2a.o \
./sofa/tf2d.o \
./sofa/tr.o \
./sofa/trxp.o \
./sofa/trxpv.o \
./sofa/tttai.o \
./sofa/tttcg.o \
./sofa/tttdb.o \
./sofa/ttut1.o \
./sofa/ut1tai.o \
./sofa/ut1tt.o \
./sofa/ut1utc.o \
./sofa/utctai.o \
./sofa/utcut1.o \
./sofa/xy06.o \
./sofa/xys00a.o \
./sofa/xys00b.o \
./sofa/xys06a.o \
./sofa/zp.o \
./sofa/zpv.o \
./sofa/zr.o 

C_DEPS += \
./sofa/a2af.d \
./sofa/a2tf.d \
./sofa/ab.d \
./sofa/af2a.d \
./sofa/anp.d \
./sofa/anpm.d \
./sofa/apcg.d \
./sofa/apcg13.d \
./sofa/apci.d \
./sofa/apci13.d \
./sofa/apco.d \
./sofa/apco13.d \
./sofa/apcs.d \
./sofa/apcs13.d \
./sofa/aper.d \
./sofa/aper13.d \
./sofa/apio.d \
./sofa/apio13.d \
./sofa/atci13.d \
./sofa/atciq.d \
./sofa/atciqn.d \
./sofa/atciqz.d \
./sofa/atco13.d \
./sofa/atic13.d \
./sofa/aticq.d \
./sofa/aticqn.d \
./sofa/atio13.d \
./sofa/atioq.d \
./sofa/atoc13.d \
./sofa/atoi13.d \
./sofa/atoiq.d \
./sofa/bi00.d \
./sofa/bp00.d \
./sofa/bp06.d \
./sofa/bpn2xy.d \
./sofa/c2i00a.d \
./sofa/c2i00b.d \
./sofa/c2i06a.d \
./sofa/c2ibpn.d \
./sofa/c2ixy.d \
./sofa/c2ixys.d \
./sofa/c2s.d \
./sofa/c2t00a.d \
./sofa/c2t00b.d \
./sofa/c2t06a.d \
./sofa/c2tcio.d \
./sofa/c2teqx.d \
./sofa/c2tpe.d \
./sofa/c2txy.d \
./sofa/cal2jd.d \
./sofa/cp.d \
./sofa/cpv.d \
./sofa/cr.d \
./sofa/d2dtf.d \
./sofa/d2tf.d \
./sofa/dat.d \
./sofa/dtdb.d \
./sofa/dtf2d.d \
./sofa/eceq06.d \
./sofa/ecm06.d \
./sofa/ee00.d \
./sofa/ee00a.d \
./sofa/ee00b.d \
./sofa/ee06a.d \
./sofa/eect00.d \
./sofa/eform.d \
./sofa/eo06a.d \
./sofa/eors.d \
./sofa/epb.d \
./sofa/epb2jd.d \
./sofa/epj.d \
./sofa/epj2jd.d \
./sofa/epv00.d \
./sofa/eqec06.d \
./sofa/eqeq94.d \
./sofa/era00.d \
./sofa/fad03.d \
./sofa/fae03.d \
./sofa/faf03.d \
./sofa/faju03.d \
./sofa/fal03.d \
./sofa/falp03.d \
./sofa/fama03.d \
./sofa/fame03.d \
./sofa/fane03.d \
./sofa/faom03.d \
./sofa/fapa03.d \
./sofa/fasa03.d \
./sofa/faur03.d \
./sofa/fave03.d \
./sofa/fk52h.d \
./sofa/fk5hip.d \
./sofa/fk5hz.d \
./sofa/fw2m.d \
./sofa/fw2xy.d \
./sofa/g2icrs.d \
./sofa/gc2gd.d \
./sofa/gc2gde.d \
./sofa/gd2gc.d \
./sofa/gd2gce.d \
./sofa/gmst00.d \
./sofa/gmst06.d \
./sofa/gmst82.d \
./sofa/gst00a.d \
./sofa/gst00b.d \
./sofa/gst06.d \
./sofa/gst06a.d \
./sofa/gst94.d \
./sofa/h2fk5.d \
./sofa/hfk5z.d \
./sofa/icrs2g.d \
./sofa/ir.d \
./sofa/jd2cal.d \
./sofa/jdcalf.d \
./sofa/ld.d \
./sofa/ldn.d \
./sofa/ldsun.d \
./sofa/lteceq.d \
./sofa/ltecm.d \
./sofa/lteqec.d \
./sofa/ltp.d \
./sofa/ltpb.d \
./sofa/ltpecl.d \
./sofa/ltpequ.d \
./sofa/num00a.d \
./sofa/num00b.d \
./sofa/num06a.d \
./sofa/numat.d \
./sofa/nut00a.d \
./sofa/nut00b.d \
./sofa/nut06a.d \
./sofa/nut80.d \
./sofa/nutm80.d \
./sofa/obl06.d \
./sofa/obl80.d \
./sofa/p06e.d \
./sofa/p2pv.d \
./sofa/p2s.d \
./sofa/pap.d \
./sofa/pas.d \
./sofa/pb06.d \
./sofa/pdp.d \
./sofa/pfw06.d \
./sofa/plan94.d \
./sofa/pm.d \
./sofa/pmat00.d \
./sofa/pmat06.d \
./sofa/pmat76.d \
./sofa/pmp.d \
./sofa/pmpx.d \
./sofa/pmsafe.d \
./sofa/pn.d \
./sofa/pn00.d \
./sofa/pn00a.d \
./sofa/pn00b.d \
./sofa/pn06.d \
./sofa/pn06a.d \
./sofa/pnm00a.d \
./sofa/pnm00b.d \
./sofa/pnm06a.d \
./sofa/pnm80.d \
./sofa/pom00.d \
./sofa/ppp.d \
./sofa/ppsp.d \
./sofa/pr00.d \
./sofa/prec76.d \
./sofa/pv2p.d \
./sofa/pv2s.d \
./sofa/pvdpv.d \
./sofa/pvm.d \
./sofa/pvmpv.d \
./sofa/pvppv.d \
./sofa/pvstar.d \
./sofa/pvtob.d \
./sofa/pvu.d \
./sofa/pvup.d \
./sofa/pvxpv.d \
./sofa/pxp.d \
./sofa/refco.d \
./sofa/rm2v.d \
./sofa/rv2m.d \
./sofa/rx.d \
./sofa/rxp.d \
./sofa/rxpv.d \
./sofa/rxr.d \
./sofa/ry.d \
./sofa/rz.d \
./sofa/s00.d \
./sofa/s00a.d \
./sofa/s00b.d \
./sofa/s06.d \
./sofa/s06a.d \
./sofa/s2c.d \
./sofa/s2p.d \
./sofa/s2pv.d \
./sofa/s2xpv.d \
./sofa/sepp.d \
./sofa/seps.d \
./sofa/sp00.d \
./sofa/starpm.d \
./sofa/starpv.d \
./sofa/sxp.d \
./sofa/sxpv.d \
./sofa/taitt.d \
./sofa/taiut1.d \
./sofa/taiutc.d \
./sofa/tcbtdb.d \
./sofa/tcgtt.d \
./sofa/tdbtcb.d \
./sofa/tdbtt.d \
./sofa/tf2a.d \
./sofa/tf2d.d \
./sofa/tr.d \
./sofa/trxp.d \
./sofa/trxpv.d \
./sofa/tttai.d \
./sofa/tttcg.d \
./sofa/tttdb.d \
./sofa/ttut1.d \
./sofa/ut1tai.d \
./sofa/ut1tt.d \
./sofa/ut1utc.d \
./sofa/utctai.d \
./sofa/utcut1.d \
./sofa/xy06.d \
./sofa/xys00a.d \
./sofa/xys00b.d \
./sofa/xys06a.d \
./sofa/zp.d \
./sofa/zpv.d \
./sofa/zr.d 


# Each subdirectory must supply rules for building sources it contributes
sofa/%.o: ../sofa/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM GNU C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DUSE_FULL_ASSERT -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -DSTM32F405xx -DUSE_HAL_DRIVER -DHSE_VALUE=8000000 -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/sofa" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/src" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/src/drivers" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/src/library" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/src/modules" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/system/include/stm32f4-hal" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/include" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/system/include" -I"/home/developer/workspace-stm32/Unica_2018_STM32F405/system/include/cmsis" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


